%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
%  Dateiname:         Daten_filter.m
%
%  Projekt:           Identifikationssystem
%
%  Kurzbeschreibung:  Diese Funktion realisiert einen Tiefpassfilter.
%
%  Datum:             21-01-2003
%
%  Autor:             Jerzy Wykretowicz
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function Daten_filter(arg)
global d hp1 h0 H_mainAxes1 koordinaten
persistent xy cp  a1 a2 f3 l1 l2 l3 l4 l5 l6 e1 e2 e5 e6 s1 s2 s5 s6 pos1 pos2 tol stack sc
persistent ax2faktor
if(nargin==0)
   BR      = 15;               % border
   ax2faktor = 5;                                 % Multiplikator für Axes2 'YLim' berechnung
   %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
   %%%%%%%%%%%%%%%%%%%%%%%%%%%%        Figure                   %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
   %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
   f3 = figure('Units','Pixels', ...
      'Color',get(0,'defaultUicontrolBackgroundColor'), ...
      'Position',[80 100 900 510], ...
      'WindowButtonMotionFcn','',...
      'DoubleBuffer','on',...
      'Resize','off',...
      'CurrentObject',gcf,...
      'MenuBar','none',...
      'NumberTitle','off',...
      'Name',' Datenvorverarbeitung Butterworth-Tiefpaß-Filter',...
      'Tag','Fig2', ...
      'ToolBar','none');
   %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
   %%%%%%%%%%%%%%%%%%%%%%%%%%%%         Axes                    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
   %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
   a1 = axes('Parent',f3, ...
      'Units','Pixels', ...
      'Color',[1 1 1], ...
      'Position',[3*BR 5*BR 825 410], ...
      'ButtonDownFcn','',...
      'Tag','Axes1');
   %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
   %%%%%%%%%%%%%%%%%%%%%%%%%%%%        Buttons                  %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
   %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
   h1 = uicontrol('Parent',f3, ...
      'Units','Pixels', ...
      'Position',[355 BR 90 23], ...
      'String','Übernehmen', ...
      'Callback','Daten_filter uebernehmen',...
      'Tag','Pushbutton4');
   h1 = uicontrol('Parent',f3, ...
      'Units','Pixels', ...
      'Position',[460 BR 90 23], ...
      'String','Zurück', ...
      'Callback','Daten_filter zurueck',...
      'Tag','Pushbutton3');
   h1 = uicontrol('Parent',f3, ...
      'Units','Pixels', ...
      'Position',[675 BR 90 23], ...
      'Callback','h = findobj( 0, ''Tag'',''Fig2'');close (h);',...
      'String','Abbrechen', ...
      'Tag','Pushbutton2');
   h1 = uicontrol('Parent',f3, ...
      'Units','Pixels', ...
      'Position',[780 BR 90 23], ...
      'String','Ok', ...
      'Callback','Daten_filter ok',...
      'Tag','Pushbutton1');
   %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
   %%%%%%%%%%%%%%%%%%%%%%%%%%%%        Edits                    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
   %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
   t1 = uicontrol('Parent',f3, ...
      'Units','Pixels', ...
      'Position',[3*BR BR+1 80 20], ...
      'String','Filterordnung:',...
      'HorizontalAlignment','left',...
      'Style','text', ...
      'Tag','text1');
   e1 = uicontrol('Parent',f3, ...
      'Units','Pixels', ...
      'BackgroundColor',[1 1 1], ...
      'Position',[130 BR+3 40 22], ...
      'Callback','Daten_filter edit1',...
      'Style','edit', ...
      'Tag','EditText1');
   %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
   t2 = uicontrol('Parent',f3, ...
      'Units','Pixels', ...
      'Position',[175 BR+1 100 20], ...
      'String','Grenzfrequenz:',...
      'HorizontalAlignment','left',...
      'Style','text', ...
      'Tag','text2');
   e2 = uicontrol('Parent',f3, ...
      'Units','Pixels', ...
      'BackgroundColor',[1 1 1], ...
      'Position',[ 270 BR+3 60 22], ...
      'Callback','Daten_filter edit2',...
      'Style','edit', ...
      'Tag','EditText1');
   %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
   sc=1;
   stack(sc).t = d.t;
   stack(sc).u = d.uerr;
   stack(sc).y = d.ySystem;
   datalaenge = length(stack(sc).t);
   stack(sc).XLim = [0 stack(sc).t(datalaenge)];
   hp=plot(stack(sc).t,stack(sc).y,'color',[0 0.5 0]);grid;legend('ungefiltert',0);
   set(a1,'XLim',stack(sc).XLim);
   stack(sc).YLim_y=get(a1,'YLim');

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%        Übernehmen               %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
elseif strcmp(arg,'uebernehmen')

   tmp1  = str2num(get(e1,'String'));
   if (isreal(tmp1) & isnumeric(tmp1) & (length(tmp1)==1) & (tmp1>0) )
      if (tmp1>5)
          tmp1=5;
      end
      tmp1=round(tmp1); 
      set(e1,'String',num2str(tmp1));
      tmp2  = str2num(get(e2,'String'));
      if (isreal(tmp2) & isnumeric(tmp2) & (length(tmp2)==1) & (tmp2>0))
         [b,a]=butter(tmp1,2*pi*tmp2,'s');
         stack(sc+1)=stack(sc);
         stack(sc+1).y=(lsim(b,a,stack(sc).y,stack(sc).t))';
         sc=sc+1;
         hp=plot(stack(1).t,stack(1).y,'b',stack(sc).t,stack(sc).y,'r');grid;
         set(a1,'XLim',stack(sc).XLim);
         set(hp(1),'color',[0 0.5 0]);
         legend('ungefiltert','Butterworth-Filter',0);
      else
         set(e2,'String','');
      end
   else
      set(e1,'String','');
   end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%        Zurück                   %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
elseif strcmp(arg,'zurueck')
   if(sc > 1)
      sc = sc-1;
      if(sc == 1)
         hp=plot(stack(1).t,stack(1).y,'color',[0 0.5 0]);grid;legend('ungefiltert',0);
         set(a1,'XLim',stack(sc).XLim);
      else
         hp=plot(stack(1).t,stack(1).y,'b',stack(sc).t,stack(sc).y,'r');grid;
         set(a1,'XLim',stack(sc).XLim);
         set(hp(1),'color',[0 0.5 0]);
         legend('ungefiltert','Butterworth-Filter',0);
      end
   end    
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%        Ok                       %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
elseif strcmp(arg,'ok')
   if(sc==1)
      close(f3);
      return;
   end
   d.t = stack(sc).t;
   d.uerr = stack(sc).u;
   d.ySystem = stack(sc).y;
   d.XLim = stack(sc).XLim;
   d.YLim = [min(stack(sc).YLim_y(1) , min(stack(sc).u))  max(stack(sc).YLim_y(2) ,...
      max(stack(sc).u))];
   d.YLim(1) = d.YLim(1)-0.1*d.YLim(2);
   d.YLim(2) = 1.1*d.YLim(2);
   close(f3);
   figure(h0);
   set(gcf,'CurrentAxes',H_mainAxes1);          
   hp1=plot(d.t,d.uerr,d.t,d.ySystem);
   set(H_mainAxes1,'XLim',d.XLim,'YLim',d.YLim);
   grid;
   set(hp1,'LineWidth',1);
   legend('Erregung','Antwort',0);
   h_btn = findobj(0,'tag','Pushbutton_setparam');     % Erst wenn zu identifizierendes System
   set(h_btn,'enable','on');                      % geladen ist, kann man Modell-Fuktion bilden
   h_btn = findobj(0,'tag','Pushbutton_Bearbeiten');   % Erst wenn zu identifizierendes System
   set(h_btn,'enable','on');                           % geladen ist, kann man es bearbeiten
   %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
end

