%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
%  Dateiname:         Modell_erstellen.m
%
%  Projekt:           Identifikationssystem
%
%  Kurzbeschreibung:  Diese Funktion realisiert das Modul "Modell erstellen". In einem GUI
%                     werden die Modellelemente eigestellt oder ein Modell wird aus einer 
%                     Datei geladen. 
%
%  Datum:             21-01-2003
%
%  Autor:             Jerzy Wykretowicz
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function Modell_ordnung()

global param2 

POSITION    = [100 350 660 175];
TEXT_XPOS = 0.3;

BR      = 15;              % border
AH      = 50;              % Axes hight
AW      = 200;             % Axes width
BDIFF   = 15;              % block-position X  difference 
PE1     = 70;              % 1-st 'edits' block x-position
PE2     = PE1+BDIFF;       % 2-nd 'edits' block x-position
PE3     = PE2+BDIFF;       % 3-rd 'edits' block x-position

h0 = figure('Units','pixels', ...
   'Color',get(0,'defaultUicontrolBackgroundColor'),...
   'Position',POSITION, ...
   'MenuBar','none',...
   'NumberTitle','off',...
   'WindowStyle','modal',...
   'Resize','off',...
   'Tag','setorder_fig', ...
   'Name',' Modellstruktur',...
   'ToolBar','none');
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%         s                   %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
h1 = uicontrol('Parent',h0, ...
   'Units','pixels', ...
   'BackgroundColor',[1 1 1], ...
   'ListboxTop',0, ...
   'Position',[BR+140 56+BR+AH 50 30], ...
   'String',' 0| 1| 2| 3| 4| 5', ...
   'Style','popupmenu', ...
   'Tag','PopupMenu2', ...
   'Value',param2(2));
h1 = axes('Parent',h0, ...
   'Units','pixels', ...
   'Box','on', ...
   'CameraUpVector',[0 1 0], ...
   'Color',[0.75 0.75 0.75], ...
   'Position',[BR 46+BR+AH AW AH], ...
   'Tag','Axes2', ...
   'TickLength',[0 0], ...
   'XColor',[0 0 0], ...
   'XLimMode','manual', ...
   'XTickMode','manual', ...
   'YColor',[0 0 0], ...
   'YTickMode','manual', ...
   'ZColor',[0 0 0]);
h2 = text('Parent',h1, ...
   'Color',[0 0 0], ...
   'Position',[TEXT_XPOS 0.5 0], ...
   'String','\bf\fontsize{10}s', ...
   'HorizontalAlignment','center', ...
   'Tag','Axes2Text1');
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%         1+sT                %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
h1 = uicontrol('Parent',h0, ...
   'Units','pixels', ...
   'BackgroundColor',[1 1 1], ...
   'ListboxTop',0, ...
   'Position',[BR+AW+BDIFF+140 56+1*BR+AH 50 30], ...
   'String',' 0| 1| 2| 3| 4| 5', ...
   'Style','popupmenu', ...
   'Tag','PopupMenu4', ...
   'Value',param2(4));
h1 = axes('Parent',h0, ...
   'Units','pixels', ...
   'Box','on', ...
   'CameraUpVector',[0 1 0], ...
   'Color',[0.75 0.75 0.75], ...
   'Position',[BR+AW+BDIFF 46+1*BR+AH AW AH], ...
   'Tag','Axes4', ...
   'TickLength',[0 0], ...
   'XColor',[0 0 0], ...
   'XLimMode','manual', ...
   'XTickMode','manual', ...
   'YColor',[0 0 0], ...
   'YTickMode','manual', ...
   'ZColor',[0 0 0]);
h2 = text('Parent',h1, ...
   'Color',[0 0 0], ...
   'Position',[TEXT_XPOS 0.5 0], ...
   'String','\bf\fontsize{10}1+sT', ...
    'HorizontalAlignment','center', ...
   'Tag','Axes4Text1');
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%         1+2dTs+(Ts)^2       %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
h1 = uicontrol('Parent',h0, ...
   'Units','pixels', ...
   'BackgroundColor',[1 1 1], ...
   'ListboxTop',0, ...
   'Position',[BR+2*(AW+BDIFF)+140 56+BR+AH 50 30], ...
   'String',' 0| 1| 2', ...
   'Style','popupmenu', ...
   'Tag','PopupMenu5', ...
   'Value',param2(5));
h1 = axes('Parent',h0, ...
   'Units','pixels', ...
   'Box','on', ...
   'CameraUpVector',[0 1 0], ...
   'Color',[0.75 0.75 0.75], ...
   'Position',[BR+2*(AW+BDIFF) 46+BR+AH AW AH], ...
   'Tag','Axes5', ...
   'TickLength',[0 0], ...
   'XColor',[0 0 0], ...
   'XLimMode','manual', ...
   'XTickMode','manual', ...
   'YColor',[0 0 0], ...
   'YTickMode','manual', ...
   'ZColor',[0 0 0]);
h2 = text('Parent',h1, ...
   'Color',[0 0 0], ...
   'Position',[TEXT_XPOS 0.5 0], ...
   'String','\bf\fontsize{10}1+2dTs+(Ts)^2', ...
    'HorizontalAlignment','center', ...
   'Tag','Axes5Text1');
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%         1/s                 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
h1 = uicontrol('Parent',h0, ...
   'Units','pixels', ...
   'BackgroundColor',[1 1 1], ...
   'ListboxTop',0, ...
   'Position',[BR+140 56 50 30], ...
   'String',' 0| 1| 2| 3| 4| 5', ...
   'Style','popupmenu', ...
   'Tag','PopupMenu3', ...
   'Value',param2(3));
h1 = axes('Parent',h0, ...
   'Units','pixels', ...
   'Box','on', ...
   'CameraUpVector',[0 1 0], ...
   'Color',[0.75 0.75 0.75], ...
   'Position',[BR 46 AW AH], ...
   'Tag','Axes1', ...
   'TickLength',[0 0], ...
   'XColor',[0 0 0], ...
   'XLimMode','manual', ...
   'XTickMode','manual', ...
   'YColor',[0 0 0], ...
   'YTickMode','manual', ...
   'ZColor',[0 0 0]);
h2 = text('Parent',h1, ...
   'Color',[0 0 0], ...
   'Position',[TEXT_XPOS 0.75 0], ...
   'String','\bf\fontsize{10}1', ...
    'HorizontalAlignment','center', ...
   'Tag','Axes6Text3');
h2 = text('Parent',h1, ...
   'Color',[0 0 0], ...
    'Position',[TEXT_XPOS 0.5 0], ...
    'String','\fontsize{3}--------', ...
    'HorizontalAlignment','center', ...
   'Tag','Axes6Text2');
h2 = text('Parent',h1, ...
   'Color',[0 0 0], ...
   'Position',[TEXT_XPOS 0.25 0], ...
   'String','\bf\fontsize{10}s', ...
    'HorizontalAlignment','center', ...
   'Tag','Axes3Text1');
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%         1/1+sT              %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
h1 = uicontrol('Parent',h0, ...
   'Units','pixels', ...
   'BackgroundColor',[1 1 1], ...
   'ListboxTop',0, ...
   'Position',[BR+(AW+BDIFF)+140 56 50 30], ...
   'String',' 0| 1| 2| 3| 4| 5', ...
   'Style','popupmenu', ...
   'Tag','PopupMenu6', ...
   'Value',param2(6));
h1 = axes('Parent',h0, ...
   'Units','pixels', ...
   'Box','on', ...
   'CameraUpVector',[0 1 0], ...
   'Color',[0.75 0.75 0.75], ...
   'Position',[BR+(AW+BDIFF) 46 AW AH], ...
   'Tag','Axes6', ...
   'TickLength',[0 0], ...
   'XColor',[0 0 0], ...
   'XLimMode','manual', ...
   'XTickMode','manual', ...
   'YColor',[0 0 0], ...
   'YTickMode','manual', ...
   'ZColor',[0 0 0]);
h2 = text('Parent',h1, ...
   'Color',[0 0 0], ...
   'Position',[TEXT_XPOS 0.75 0], ...
   'String','\bf\fontsize{10}1', ...
    'HorizontalAlignment','center', ...
   'Tag','Axes6Text3');
h2 = text('Parent',h1, ...
   'Color',[0 0 0], ...
    'Position',[TEXT_XPOS 0.5 0], ...
    'String','\fontsize{3}--------------------', ...
    'HorizontalAlignment','center', ...
   'Tag','Axes6Text2');
h2 = text('Parent',h1, ...
   'Color',[0 0 0], ...
   'Position',[TEXT_XPOS 0.25 0], ...
   'String','\bf\fontsize{10}1+sT', ...
    'HorizontalAlignment','center', ...
   'Tag','Axes6Text1');
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%       1/1+2dTs+(Ts)^2         %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
h1 = uicontrol('Parent',h0, ...
   'Units','pixels', ...
   'Position',[BR+2*(AW+BDIFF)+140 56 50 30], ...
   'BackgroundColor',[1 1 1], ...
   'ListboxTop',0, ...
   'String',' 0| 1| 2', ...
   'Style','popupmenu', ...
   'Tag','PopupMenu7', ...
   'Value',param2(7));
h1 = axes('Parent',h0, ...
   'Units','pixels', ...
   'Box','on', ...
   'CameraUpVector',[0 1 0], ...
   'Color',[0.75 0.75 0.75], ...
   'Position',[BR+2*(AW+BDIFF) 46 AW AH], ...
   'Tag','Axes7', ...
   'TickLength',[0 0], ...
   'XColor',[0 0 0], ...
   'XLimMode','manual', ...
   'XTickMode','manual', ...
   'YColor',[0 0 0], ...
   'YTickMode','manual', ...
   'ZColor',[0 0 0]);
h2 = text('Parent',h1, ...
   'Color',[0 0 0], ...
   'Position',[TEXT_XPOS 0.78 0], ...
   'String','\bf\fontsize{10}1', ...
     'HorizontalAlignment','center', ...
   'Tag','Axes7Text3');
h2 = text('Parent',h1, ...
   'Color',[0 0 0], ...
   'Position',[TEXT_XPOS 0.53 0], ...
   'String','\fontsize{3}--------------------------------------------------', ...
   'HorizontalAlignment','center', ...
   'Tag','Axes7Text2');
h2 = text('Parent',h1, ...
   'Color',[0 0 0], ...
   'Position',[TEXT_XPOS 0.28 0], ...
   'String','\bf\fontsize{10}1+2dTs+(Ts)^2', ...
   'HorizontalAlignment','center', ...
   'Tag','Axes7Text1');
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%       Pushbuttons           %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
h1 = uicontrol('Parent',h0, ...
   'Units','pixels', ...
   'ListboxTop',0, ...
   'Position',[POSITION(3)-90-BR 10 90 25], ...
   'String','Ok', ...
   'Callback','Modellord_check', ...
   'Tag','Pushbutton1');
h1 = uicontrol('Parent',h0, ...
   'Units','pixels', ...
   'ListboxTop',0, ...
   'Position',[POSITION(3)-200-BR 10 90 25], ...
   'String','Abbrechen', ...
   'Callback','close', ...
   'Tag','Pushbutton1');
h1 = uicontrol('Parent',h0, ...
   'Units','pixels', ...
   'Callback','Modell_laden', ...
   'ListboxTop',0, ...
   'Position',[BR 10 90 25], ...
   'String','Aus Datei ...', ...
   'Tag','Pushbutton1');
if nargout > 0, fig = h0; end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%             Ende            %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
