%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
%  Dateiname:         Steuermodul.m
%
%  Projekt:           Identifikationssystem
%
%  Kurzbeschreibung:  Diese Funktion realisiert das Modul "steuermodul". Hier wird das 
%                     Standardoberfläche des Programms erstellt.  
%
%  Datum:             21-01-2003
%
%  Autor:             Jerzy Wykretowicz
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function fig = steuermodul()

global param2 H_mainAxes1 H_mainAxes2 H_mainAxes3 h_tp h_dp h_vp h_ic
global FIGCOL h_iterNr h_patch h_iterEdit
global d opt defopt h_histView  oldCoor oldValue h0
   
warning off
BW      = 125;              % BUTTON_WIDTH
BH      = 23;               % BUTTON_HIGHT 
FW      = 900;              % figure width
FH      = 650;              % figure hight
EW      = 75;               % edit width
BR      = 15;               % border
FRCOL   = [0 0 0];          % frames color
XDIFF   = 7;                % text- and edit-position X difference 
YDIFF   = 5;                % text- and edit-position Y difference 
BDIFF   = 120;              % block-position X  difference 
EDIFF   = 26;               % 'edit' Y difference
PBY     = 137;              % 1-st 'edit'  y-position
PE1      = 70;              % 1-st 'edits' block x-position
PE2      = PE1+BDIFF;       % 2-nd 'edits' block x-position
PE3      = PE2+BDIFF;       % 3-rd 'edits' block x-position
PE4      = PE3+BDIFF;       % 4-th 'edits' block x-position
PT1      = PE1-30;          % 1-st 'text'  block x-position
PT2      = PE2-30;          % 2-nd 'text'  block x-position
PT3      = PE3-30;          % 3-rd 'text'  block x-position
PT4      = PE4-30;          % 4-th 'text'  block x-position
param2=ones(1,7);
oldCoor=0;
oldValue=1;

%%%%%%%%%%%%%%%%%%%%%%% Suchfunktion Default Optionen %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
defopt.maxfuneval  = 500;       % maximale Anzahl der Zielfunktionsevaluationen      
defopt.maxiter     = 500;       % maximale Anzahl der Suchfunktioniterationen 
defopt.tolx        = 1e-4;      % angestrebte Parametertoleranz
defopt.tolfun      = 1e-4;      % angestrebte Funktionswerttoleranz
defopt.refresh     = 5;         % Auffrischungsrate    

opt=defopt;                      

set(0,'DefaultFigureUnits','pixels');
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%       Figure      %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
h0 = figure('FileName','main2.m', ...
    'Position',[25 50 900 650], ...
    'Resize','off',...
    'MenuBar','none',...
    'NumberTitle','off',...
    'Name',' Systemidentifikation',...
    'Tag','Fig1', ...
    'Color',get(0,'defaultUicontrolBackgroundColor'),...
    'ToolBar','none');
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%       Plot Axes          %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
H_mainAxes1 = axes('Parent',h0, ...
    'Units','Pixels', ...
    'Color',[1 1 1], ...
    'Position',[2*BR, 350, 507, 280], ...
    'DrawMode','fast',...
    'FontSize',8,...
    'Tag','mainAxes1');   
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%       Modell TF Frame        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
H_mainAxes2 = axes('Parent',h0, ...
    'Units','Pixels', ...
    'Box','on', ...
    'Position',[2*BR, 200, 675, 107], ...
    'Color',get(0,'defaultUicontrolBackgroundColor'), ...
    'TickLength',[0 0], ...
    'XTick',0, ...
    'XTickLabelMode','manual', ...
    'YTick',0, ...
    'YTickLabelMode','manual', ...
    'YColor',FRCOL,...
    'XColor',FRCOL,...
    'XLimMode','manual',...
    'YLimMode','manual',...
    'XLim',[0 607],...
    'YLim',[0 100],...
    'Tag','mainAxes2');
id_text1 = text('Parent',H_mainAxes2, ...
    'Color',[0 0 0], ...
    'HorizontalAlignment','center', ...
    'Position',[35 50], ...
    'HandleVisibility','off', ...
    'Tag','id_text1', ...
    'String','\bf\fontsize{12}G\bf\fontsize{10}(s) \rm=');
h1 = uicontrol('Parent',h0, ...
    'Units','Pixels', ...
    'Position',[36, 297, 280, 20], ...
    'String','Modell-Übertragungsfunktion in V-Normalform', ...
    'Style','text', ...
    'Tag','frame_label1');
set(H_mainAxes2,'HandleVisibility','off');
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    %%%%%%%%        Modell Frame Buttons    %%%%%%%%%%%%%
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
frame4_coor = get(H_mainAxes2,'Position');
h1 = uicontrol('Parent',h0, ...
    'Units','Pixels', ...
    'HandleVisibility','on', ...
    'TooltipString','Modell-Übertragunsfunktion laden',... 
    'Callback','Modell_erstellen', ...
    'Position',[frame4_coor(1)+frame4_coor(3)-BR-BW,frame4_coor(2)+10+28*2, BW, BH], ...
    'Enable','off',...
    'String','Modellstruktur wählen', ...
    'Tag','Pushbutton_setparam');
h1 = uicontrol('Parent',h0, ...
    'Units','Pixels', ...
    'HandleVisibility','on', ...
    'TooltipString','Modell-Übertragunsfunktion speichern',... 
    'Callback','Modell_speichern', ...
    'Position',[frame4_coor(1)+frame4_coor(3)-BR-BW,frame4_coor(2)+10+28*1, BW, BH], ...
    'Enable','off',...
    'String','Modell Speichern', ...
    'Tag','Pushb_Mod_Speichern');
h1 = uicontrol('Parent',h0, ...
    'Units','Pixels', ...
    'HandleVisibility','on', ...
    'TooltipString','Modell-Simulation',... 
    'Callback','Modell_simulation', ...
    'Position',[frame4_coor(1)+frame4_coor(3)-BR-BW,frame4_coor(2)+10, BW, BH], ...
    'Enable','off',...
    'String','Modell Simulieren', ...
    'Tag','Pushbutton_Simulation');
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%       Daten Frame        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
H_frame1 = axes('Parent',h0, ...
    'Units','Pixels', ...
    'Box','on', ...
    'Position',[FW-3*BR-BW, 1*BR, BW+2*BR, 292], ...
    'Color',get(0,'defaultUicontrolBackgroundColor'), ...
    'TickLength',[0 0], ...
    'XTick',0, ...
    'XTickLabelMode','manual', ...
    'YTick',0, ...
    'YTickLabelMode','manual', ...
    'YColor',FRCOL,...
    'XColor',FRCOL,...
    'HandleVisibility','off',...
    'Tag','Frame1');
h1 = uicontrol('Parent',h0, ...
    'Units','Pixels', ...
    'Position',[FW-3*BR-BW+5, 292, 45, 23], ...
    'String','Daten', ...
    'Style','text', ...
    'Tag','Datenframe_label');
frame1_coor = get(H_frame1,'Position');
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    %%%%%%%%        Daten Frame Buttons      %%%%%%%%%%%%
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
h1 = uicontrol('Parent',h0, ...
    'Units','Pixels', ...
    'Callback','Daten_laden', ...
    'HorizontalAlignment','right', ...
    'ListboxTop',0, ...
    'Position',[frame1_coor(1:2)+[BR,BR+12+8*28], BW, BH], ...
    'String',['Laden        ';'Aus Workspace';'Aus Datei... '], ...
    'Style','popupmenu', ...
    'Tag','PopupMenu_Laden1', ...
    'Value',1);
h1 = uicontrol('Parent',h0, ...
    'Units','Pixels', ...
    'Callback','Daten_bearbeiten', ...
    'HorizontalAlignment','right', ...
    'ListboxTop',0, ...
    'Position',[frame1_coor(1:2)+[BR,BR+12+7*28], BW, BH], ...
    'String',['Bearbeiten';'Bereich   ';'Filter    ';'Dezimieren'], ...
    'Style','popupmenu', ...
    'Enable','off',...
    'Tag','PopupMenu_Bearbeiten', ...
    'Value',1);
h1 = uicontrol('Parent',h0, ...
    'Units','Pixels', ...
    'HandleVisibility','on', ...
     'Callback','Daten_speichern', ...
    'Position',[frame1_coor(1:2)+[BR,BR+12+3*28], BW, BH], ...
    'Enable','off',...
    'String','Daten speichern', ...
    'Tag','Pushbutton_DatenSpeichern');
h1 = uicontrol('Parent',h0, ...
    'Units','Pixels', ...
    'Callback','close all', ...
    'Position',[frame1_coor(1:2)+[BR,BR], BW, BH], ...
    'String','Schließen', ...
    'Tag','Pushbutton_close');
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%       Suchfunktion Frame        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
H_frame3 = axes('Parent',h0, ...
    'Units','Pixels', ...
    'Box','on', ...
    'Position',[4*BR+507, 350, FW-5*BR-507, 280], ...
    'Color',get(0,'defaultUicontrolBackgroundColor'), ...
    'TickLength',[0 0], ...
    'XTick',0, ...
    'XTickLabelMode','manual', ...
    'YTick',0, ...
    'YTickLabelMode','manual', ...
    'YColor',FRCOL,...
    'XColor',FRCOL,...
    'HandleVisibility','off',...
    'Tag','Frame3');
h1 = uicontrol('Parent',h0, ...
    'Units','Pixels', ...
    'Position',[4*BR+507+5, 615, 80, 23], ...
    'String','Suchfunktion', ...
    'Style','text', ...
    'Tag','Suchfuntionframe_label');
frame3_coor = get(H_frame3,'Position');
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    %%%%%%%%        Suchfunktion Frame Buttons      %%%%%
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
h1 = uicontrol('Parent',h0, ...
    'Units','Pixels', ...
    'HandleVisibility','on', ...
     'Callback','Umgebungsparameter', ...
    'Position',[frame3_coor(1:2)+[frame3_coor(3)-BR-BW,BR], BW, BH], ...
    'Enable','on',...
    'String','Optionen...', ...
    'Tag','Pushbutton_Optionen');
h1 = uicontrol('Parent',h0, ...
    'Units','Pixels', ...
    'HandleVisibility','on', ...
     'Callback','set_parameter(''Stop'',0,0,0)', ...
    'Position',[frame3_coor(1:2)+[frame3_coor(3)-BR-BW,BR+1*28], BW, BH], ...
    'Enable','off',...
    'String','Stop', ...
    'Tag','Pushbutton_Stop');
h1 = uicontrol('Parent',h0, ...
    'Units','Pixels', ...
    'HandleVisibility','on', ...
     'Callback','set_parameter(''Start'',0,0,0)', ...
    'Position',[frame3_coor(1:2)+[frame3_coor(3)-BR-BW,BR+2*28], BW, BH], ...
    'Enable','off',...
    'String','Start', ...
    'Tag','Pushbutton_Start');
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    %%%%%%%%        Iteration Laufbalken            %%%%%
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
h_iterView = axes('Parent',h0, ...
    'Units','pixels', ...
    'Box','on', ...
    'CameraUpVector',[0 1 0], ...
    'CameraUpVectorMode','manual', ...
    'Color',[1 1 1], ...
    'Position',[frame3_coor(1:2)+[BR,BR+5*28], frame3_coor(3)-2*BR 23], ...
    'Tag','Iteration_Axes', ...
    'XLim',[0 100],...
    'TickLength',[0 0], ...
    'XColor',[0 0 0], ...
    'XTickMode','manual', ...
    'YColor',[0 0 0], ...
    'YTickMode','manual', ...
    'ZColor',[0 0 0]);
h1 = uicontrol('Parent',h0, ...
    'Position',[frame3_coor(1:2)+[BR,BR+6*28] 50 15], ...
    'String','Iteration', ...
    'Style','text', ...
    'Tag','IterText1');
h_iterNr = uicontrol('Parent',h0, ...
    'Position',[frame3_coor(1:2)+[265,BR+6*28] 40 15], ...
    'HorizontalAlignment','right',...
    'String','0 %', ...
    'Style','text', ...
    'Tag','IterText2');
h_patch = patch([0 0 0 0 0],[0 1 1 0 0],'r',... 
    'Parent',h_iterView, ...
    'Tag','IterPatch');
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    %%%%%%%%        Iteration Edit            %%%%%%%%%%%
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
h_iterEdit = uicontrol('Parent',h0, ...
    'Position',[frame3_coor(1:2)+[frame3_coor(3)-BR-BW,BR+7*28], BW, BH], ...
    'HorizontalAlignment','right', ...
    'BackgroundColor','w',...
    'String','', ...
    'Enable','inactive',...
    'Style','edit', ...
    'Tag','IterEdit');
h1 = uicontrol('Parent',h0, ...
    'Position',[frame3_coor(1:2)+[50,BR+7*28+5] 120 15], ...
    'HorizontalAlignment','right',...
    'String','Zielfunktionswert :', ...
    'Style','text', ...
    'Tag','IterEditText');
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    %%%%%%%%        Suchfunktionswertverlauf        %%%%%
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
h_histView = axes('Parent',h0, ...
    'Units','pixels', ...
    'Box','on', ...
    'NextPlot','add',...
    'CameraUpVector',[0 1 0], ...
    'CameraUpVectorMode','manual', ...
    'Color',[1 1 1], ...
    'Position',[frame3_coor(1:2)+[BR+10,BR],BW, 80], ...
    'Tag','Histo_Axes', ...
    'FontSize',6,...
    'XLim',[0 100],...
    'YLim',[0.95 1.05],...
    'YTick',[0.95,1,1.05],...
    'YTickLabel',{' -5%',' 0',' 5%'},...
    'TickLength',[1 0], ...
    'XColor',[0 0 0], ...
    'XTickMode','manual', ...
    'YColor',[0 0 0], ...
    'YTickMode','manual', ...
    'ZColor',[0 0 0]);
h1 = uicontrol('Parent',h0, ...
    'Position',[frame3_coor(1:2)+[BR+10,BR+3*28] 130 15], ...
    'String','Funktionswertverlauf :', ...
    'Style','text', ...
    'Tag','HistoText1');
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%       Edits Frame        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
H_frame2 = axes('Parent',h0, ...
    'Units','Pixels', ...
    'Box','on', ...
    'Position',[2*BR, 1*BR, 675, 160], ...
    'Color',get(0,'defaultUicontrolBackgroundColor'), ...
    'TickLength',[0 0], ...
    'XTick',0, ...
    'XTickLabelMode','manual', ...
    'YTick',0, ...
    'YTickLabelMode','manual', ...
    'YColor',FRCOL,...
    'XColor',FRCOL,...
    'HandleVisibility','off',...
    'Tag','Frame2');
h1 = uicontrol('Parent',h0, ...
    'Units','Pixels', ...
    'Position',[36, 163, 280, 23], ...
    'String','Parameter der Modell-Übertragungsfunktion', ...
    'Style','text', ...
    'Tag','frame_label1');
frame2_coor = get(H_frame2,'Position');
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    %%%%%%%%        1 - Edit  Block      %%%%%%%%%%%%%%%%
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
h_vp(1) = uicontrol('Parent',h0, ...
    'HorizontalAlignment','right', ...
    'Position',[PE1 PBY EW 23], ...
    'String','', ...
    'Enable','off',...
    'Style','edit', ...
    'Tag','VEdit');
h_vp(2) = uicontrol('Parent',h0, ...
    'Position',[PT1 PBY-YDIFF 25 25], ...
    'String',' V  :', ...
    'Enable','off',...
    'Style','text', ...
    'Tag','VEditText');
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    %%%%%%%%        2 - Edit  Block      %%%%%%%%%%%%%%%%
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
h_tp(1,1) = uicontrol('Parent',h0, ...
    'HorizontalAlignment','right', ...
    'Position',[PE2 PBY EW 23], ...
    'String','', ...
    'Enable','off',...
    'Style','edit', ...
    'Tag','TimeEdit1');
h_tp(1,2) = uicontrol('Parent',h0, ...
    'Position',[PT2 PBY-YDIFF 25 25], ...
    'String','T1  :', ...
    'Enable','off',...
    'Style','text', ...
    'Tag','StaticText1');
h_tp(2,1) = uicontrol('Parent',h0, ...
    'HorizontalAlignment','right', ...
    'Position',[PE2 PBY-EDIFF EW 23], ...
    'String','', ...
    'Enable','off',...
    'Style','edit', ...
    'Tag','TimeEdit1');
h_tp(2,2) = uicontrol('Parent',h0, ...
    'Position',[PT2 PBY-EDIFF-YDIFF  25 25], ...
    'String','T2  :', ...
    'Enable','off',...
    'Style','text', ...
    'Tag','StaticText2');
h_tp(3,1) = uicontrol('Parent',h0, ...
    'HorizontalAlignment','right', ...
    'Position',[PE2 PBY-2*EDIFF EW 23], ...
    'String','', ...
    'Enable','off',...
    'Style','edit', ...
    'Tag','TimeEdit3');
h_tp(3,2) = uicontrol('Parent',h0, ...
    'Position',[PT2 PBY-2*EDIFF-YDIFF  25 25], ...
    'String','T3  :', ...
    'Enable','off',...
    'Style','text', ...
    'Tag','StaticText3');
h_tp(4,1) = uicontrol('Parent',h0, ...
    'HorizontalAlignment','right', ...
    'Position',[PE2 PBY-3*EDIFF EW 23], ...
    'String','', ...
    'Enable','off',...
    'Style','edit', ...
    'Tag','TimeEdit4');
h_tp(4,2) = uicontrol('Parent',h0, ...
    'Position',[PT2 PBY-3*EDIFF-YDIFF  25 25], ...
    'String','T4  :', ...
    'Enable','off',...
    'Style','text', ...
    'Tag','StaticTex4');
h_tp(5,1) = uicontrol('Parent',h0, ...
    'HorizontalAlignment','right', ...
    'Position',[PE2 PBY-4*EDIFF EW 23], ...
    'String','', ...
    'Enable','off',...
    'Style','edit', ...
    'Tag','TimeEdit5');
h_tp(5,2) = uicontrol('Parent',h0, ...
    'Position',[PT2 PBY-4*EDIFF-YDIFF  25 25], ...
    'String','T5  :', ...
    'Enable','off',...
    'Style','text', ...
    'Tag','StaticText5');
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    %%%%%%%%        3 - Edit  Block      %%%%%%%%%%%%%%%%
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
h_tp(6,1) = uicontrol('Parent',h0, ...
    'HorizontalAlignment','right', ...
    'Position',[PE3 PBY EW 23], ...
    'String','', ...
    'Enable','off',...
    'Style','edit', ...
    'Tag','TimeEdit6');
h_tp(6,2) = uicontrol('Parent',h0, ...
    'Position',[PT3 PBY-YDIFF 25 25], ...
    'String','T6  :', ...
    'Enable','off',...
    'Style','text', ...
    'Tag','StaticText6');
h_tp(7,1) = uicontrol('Parent',h0, ...
    'HorizontalAlignment','right', ...
    'Position',[PE3 PBY-EDIFF EW 23], ...
    'String','', ...
    'Enable','off',...
    'Style','edit', ...
    'Tag','TimeEdit6');
h_tp(7,2)= uicontrol('Parent',h0, ...
    'Position',[PT3 PBY-EDIFF-YDIFF  25 25], ...
    'String','T7  :', ...
    'Enable','off',...
    'Style','text', ...
    'Tag','StaticText7');
h_tp(8,1) = uicontrol('Parent',h0, ...
    'HorizontalAlignment','right', ...
    'Position',[PE3 PBY-2*EDIFF EW 23], ...
    'String','', ...
    'Enable','off',...
    'Style','edit', ...
    'Tag','TimeEdit8');
h_tp(8,2) = uicontrol('Parent',h0, ...
    'Position',[PT3 PBY-2*EDIFF-YDIFF  25 25], ...
    'String','T8  :', ...
    'Enable','off',...
    'Style','text', ...
    'Tag','StaticText8');
h_tp(9,1) = uicontrol('Parent',h0, ...
    'HorizontalAlignment','right', ...
    'Position',[PE3 PBY-3*EDIFF EW 23], ...
    'String','', ...
    'Enable','off',...
    'Style','edit', ...
    'Tag','TimeEdit9');
h_tp(9,2) = uicontrol('Parent',h0, ...
    'Position',[PT3 PBY-3*EDIFF-YDIFF  25 25], ...
    'String','T9  :', ...
    'Enable','off',...
    'Style','text', ...
    'Tag','StaticTex9');
h_tp(10,1) = uicontrol('Parent',h0, ...
    'HorizontalAlignment','right', ...
    'Position',[PE3 PBY-4*EDIFF EW 23], ...
    'String','', ...
    'Enable','off',...
    'Style','edit', ...
    'Tag','TimeEdit10');
h_tp(10,2) = uicontrol('Parent',h0, ...
    'Position',[PT3 PBY-4*EDIFF-YDIFF  25 25], ...
    'String','T10:', ...
    'Enable','off',...
    'Style','text', ...
    'Tag','StaticText10');
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    %%%%%%%%        4 - Edit  Block      %%%%%%%%%%%%%%%%
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
h_dp(1,1) = uicontrol('Parent',h0, ...
    'HorizontalAlignment','right', ...
    'Position',[PE4 PBY EW 23], ...
    'String','', ...
    'Enable','off',...
    'Style','edit', ...
    'Tag','TimeEdit11');
h_dp(1,2) = uicontrol('Parent',h0, ...
    'Position',[PT4 PBY-YDIFF 25 25], ...
    'String','d1  :', ...
    'Enable','off',...
    'Style','text', ...
    'Tag','StaticText11');
h_dp(2,1) = uicontrol('Parent',h0, ...
    'HorizontalAlignment','right', ...
    'Position',[PE4 PBY-EDIFF EW 23], ...
    'String','', ...
    'Enable','off',...
    'Style','edit', ...
    'Tag','TimeEdit12');
h_dp(2,2) = uicontrol('Parent',h0, ...
    'Position',[PT4 PBY-EDIFF-YDIFF  25 25], ...
    'String','d2  :', ...
    'Enable','off',...
    'Style','text', ...
    'Tag','StaticText12');
h_dp(3,1) = uicontrol('Parent',h0, ...
    'HorizontalAlignment','right', ...
    'Position',[PE4 PBY-2*EDIFF EW 23], ...
    'String','', ...
    'Enable','off',...
    'Style','edit', ...
    'Tag','TimeEdit13');
h_dp(3,2) = uicontrol('Parent',h0, ...
    'Position',[PT4 PBY-2*EDIFF-YDIFF  25 25], ...
    'String','d3  :', ...
    'Enable','off',...
    'Style','text', ...
    'Tag','StaticText13');
h_dp(4,1) = uicontrol('Parent',h0, ...
    'HorizontalAlignment','right', ...
    'Position',[PE4 PBY-3*EDIFF EW 23], ...
    'String','', ...
    'Enable','off',...
    'Style','edit', ...
    'Tag','TimeEdit14');
h_dp(4,2) = uicontrol('Parent',h0, ...
    'Position',[PT4 PBY-3*EDIFF-YDIFF  25 25], ...
    'String','d4  :', ...
    'Enable','off',...
    'Style','text', ...
    'Tag','StaticTex14');
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    %%%%%%%%        Edit Frame Buttons      %%%%%%%%%%%%%
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
h_ic = uicontrol('Parent',h0, ...
    'Units','Pixels', ...
    'HandleVisibility','callback', ...
     'Callback','set_parameter(''Integrator'',0,0,0)', ...
    'Position',[frame2_coor(1)+frame2_coor(3)-BR-BW,144, BW, BH], ...
    'Enable','off',...
    'Style','checkbox',...
    'String','Fixed Integrator', ...
    'Visible','off',...
    'Tag','Integrator_Übernehmen');
h1 = uicontrol('Parent',h0, ...
    'Units','Pixels', ...
    'HandleVisibility','callback', ...
     'Callback','set_parameter(''Übernehmen'',0,0,0)', ...
    'Position',[frame2_coor(1)+frame2_coor(3)-BR-BW,frame1_coor(2)+BR+28*3, BW, BH], ...
    'Enable','off',...
    'String','Übernehmen', ...
    'Tag','Pushbutton_Übernehmen');
h1 = uicontrol('Parent',h0, ...
    'Units','Pixels', ...
    'HandleVisibility','callback', ...
     'Callback','set_parameter(''Default'',0,0,0)', ...
    'Position',[frame2_coor(1)+frame2_coor(3)-BR-BW,frame1_coor(2)+BR+28*2, BW, BH], ...
    'Enable','off',...
    'String','Default', ...
    'Tag','Pushbutton_Default');
h1 = uicontrol('Parent',h0, ...
    'Units','Pixels', ...
    'HandleVisibility','callback', ...
     'Callback','set_parameter(''Vorherige'',0,0,0)', ...
    'Position',[frame2_coor(1)+frame2_coor(3)-BR-BW,frame1_coor(2)+BR+28, BW, BH], ...
    'Enable','off',...
    'String','Vorherige', ...
    'Tag','Pushbutton_Vorherige');
figure(h0)
if nargout > 0, fig = h0; end
