%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
%  Dateiname:         Umgebungsparameter.m
%
%  Projekt:           Identifikationssystem
%
%  Kurzbeschreibung:  Diese Funktion realisiert das Modul "Umgebungsparameter". Hier werden
%                     Parameter für Suchfunktion und graphische Ausgabe eingestellt.
%
%  Datum:             21-01-2003
%
%  Autor:             Jerzy Wykretowicz
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function fig = Suchfkt_optionen()

global opt defopt h_opt
BR      = 15;              
EW      = 70;              
POSITION    = [550 450 360 230];
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%        FIGURE               %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
h0 = figure('Units','pixels', ...
   'Color',get(0,'defaultUicontrolBackgroundColor'),...
   'Position',POSITION, ...
   'MenuBar','none',...
   'NumberTitle','off',...
   'WindowStyle','modal',...
   'Resize','off',...
   'Tag','options_fig', ...
   'Name',' Suchfunktion Optionen',...
   'ToolBar','none');
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%        FRAME                %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
h1 = uicontrol('Parent',h0, ...
   'Units','pixels', ...
   'Position',[BR BR+30 POSITION(3)-2*BR 170], ...
   'Style','frame', ...
   'Tag','Frame1');
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%        TEXT                 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
h1 = uicontrol('Parent',h0, ...
   'Units','pixels', ...
   'HorizontalAlignment','left', ...
   'Position',[2*BR 60+3*40 120 23], ...
   'String','Zielfunktionsfehler:', ...
   'Style','text', ...
   'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
   'Units','pixels', ...
   'HorizontalAlignment','left', ...
   'Position',[2*BR 60+2*40 120 23], ...
   'String','Parameterfehler:', ...
   'Style','text', ...
   'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
   'Units','pixels', ...
   'HorizontalAlignment','left', ...
   'Position',[2*BR 60+40 120 23], ...
   'String','Iterationsanzahl:', ...
   'Style','text', ...
   'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
   'Units','pixels', ...
   'HorizontalAlignment','left', ...
   'Position',[2*BR 60 120 23], ...
   'String',' Auffrischungsfaktor:', ...
   'Style','text', ...
   'Tag','StaticText1');
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%        EDIT                 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
h_opt(1) = uicontrol('Parent',h0, ...
   'Units','pixels', ...
   'BackgroundColor',[1 1 1], ...
   'Position',[POSITION(3)-2*BR-100 60+3*40 100 23], ...
   'Style','edit', ...
   'HorizontalAlignment','right', ...
   'String',num2str(opt.tolfun),...
   'Tag','Edit_fun');
h_opt(2) = uicontrol('Parent',h0, ...
   'Units','pixels', ...
   'BackgroundColor',[1 1 1], ...
   'Position',[POSITION(3)-2*BR-100 60+2*40 100 23], ...
   'Style','edit', ...
   'HorizontalAlignment','right', ...
   'String',num2str(opt.tolx),...
   'Tag','Edit_x');
h_opt(3) = uicontrol('Parent',h0, ...
   'Units','pixels', ...
   'BackgroundColor',[1 1 1], ...
   'Position',[POSITION(3)-2*BR-100 60+40 100 23], ...
   'Style','edit', ...
   'HorizontalAlignment','right', ...
   'String',num2str(opt.maxfuneval),...
   'Tag','Edit_iter');
h_opt(4) = uicontrol('Parent',h0, ...
   'Units','pixels', ...
   'BackgroundColor',[1 1 1], ...
   'Position',[POSITION(3)-2*BR-100 60 100 23], ...
   'Style','edit', ...
   'HorizontalAlignment','right', ...
   'String',num2str(opt.refresh),...
   'Tag','Edit_refresh');
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%        BUTTONS               %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
h1 = uicontrol('Parent',h0, ...
   'Units','pixels', ...
   'ListboxTop',0, ...
   'Position',[POSITION(3)-100-BR 10 100 25], ...
   'Callback','Suchfktopt_check(''change'')', ...
   'String','Ok', ...
   'Tag','Pushbutton1');
h1 = uicontrol('Parent',h0, ...
   'Units','pixels', ...
   'Position',[POSITION(3)-200-2*BR 10 100 25], ...
   'Callback','close', ...
   'String','Abbrechen', ...
   'Tag','Pushbutton1');
h1 = uicontrol('Parent',h0, ...
   'Units','pixels', ...
   'Position',[BR 10 100 25], ...
   'Callback','Suchfktopt_check(''default'')', ...
   'String','Default', ...
   'Tag','Pushbutton1');   
if nargout > 0, fig = h0; end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%        ENDE                 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
